site_name: Microscopy Software Tools
theme:
  name: material
  features:
    - navigation.sections
    - content.code.copy

plugins:
  - mkdocstrings:
      handlers:
        python:
          setup_commands:
            - import sys
            - sys.path.append("src")